sudo: required
language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
      - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
    secure: "S8haxKk7redV9Jj+Xjl6VP++5bIvzre6X5HZKDlR7EfF3o+Gq0ZwDvwmYFDudhk2EFySdsHcbUvrOlOldq5622UYUwJyM8PsuDtfEM6Prm2KIx3D5yt629e6Dxvh4RCFAUWuhCoRO5YbSdLRfVOju1kakQx37WusEVKMQyH7wikq9roRLavnyUyHWzRLjKep6jfg+3a5aJw5rDkhgYhFzMm162zsS0xDvCJSjLiEt1CdvTUk/E85tyNjEoJFFL7IWcj7u62E7ByO3kcjNcHjffA3/6LhMB3H5AoGIL3hK9bHljAV4uaWSj0YXFFsbjbo2Z5Sb7AnvB0SzmHSob8VRu9chSoHJxZOnYN1gbQj2p0tmUvoWU5h578Dlb+obgI8hi9j4WB/0GeIZbvGNqKg05lewNpaYnNpE1ISaXpulgTFZeK3FCl09H7pUK4Lz+NZRDej2UI3HdovlNbXtyQS14MOwBCovfW6ifZAkGj2sNtx+hmqWBt7+Kr8wxoII32lko+M5gZySmaUAoQwW3s3M1cixb0U6eO5c+sg1FmKo+rboAtW6k7EpedhzwUi1u5fvNtBwwa8Cdvrx8wUem3CHhbeBF8j4WhtSKVoWS/dmz0Mwv+tTlnOc2pltvVTb4+bSmWlLOMam8TttkAm6BMeOU93AVqDvDw0P960IBWDjzg="

