sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "WOkMxMbvhfUlOcX4tbPYfwpglnI0271Uw7znzuZcgXx7U7Hl53aEscKCah5cq4M6G+w/zOWS80sCzfBTihKgrYHFCyI5+tWGGiIMh4Tf4mrI1coOM/CIMwIquC7/vbRQJmCefluG+6WdEK1DK8xpxDCsHtciwA7OnMQ/j6ziC/qPwpvylH/Wyr6wIekhAwRWfn8fN4ARiiTO/IQvREPBYTuvET/3dUW37a74FsIDdJPVtY1pG2foykDnRylK2immegt60DbFe8o89hbyI7++sWJXqeZMhm/eLBZfOV8WAdGnRVDBXYqz1yFUU7QJpiVWOgjz3Jujmt8PJ5JX8rQd3xF+wvZcD30Pu90eccDS7W0JvkdBOzfcoLgF3rqV8Zb8jEZuMIeSVmDajwScokB99bB3TDbqzFcSWb/esoohGbQ+o/Lh7VYm1PgU4gCiiLyzdFu8hNFYY9IL1jQLAEsc1cDmZFvoCZ4PoKO16a5acbhjrxZ1p7De65Iwh5lf5Yx++fQdFiJEfupq3QYLZjOvotkwKQ9ni52wg174n/av8CrjHZn+vp42womTfzwvDxYZB0SgbEwzQaTb7TR2L97KAlrzFMFljvx+7bE8XvOfS8v7ltRAPWMY+Ek4nZnWxKHdNCydCCx5DO8n56GrySfLdOaMqON7wkb3X2HztCho1+M="
  - secure: "GEu6bS8VwmQlWYJ8vEKSF+uDPCsQf0vPVWM08b1kumHh+iBZvBFFiEKd8JgK1+NJ8f75IQzxaut8rVbjFS7ML25n9FHAfItedx3Z23j/Y/LT/Zc5IyofWlypDhf5Z9TAOkY0tL0vb9Gb4Uja8z7TVQwjtaofxSvXK/1VxQwW6qqpvyumszEaWhxa9XHYlQ5yudy7qhaV6fkV/h79I7PfYypY8Omag6XYtxRu5qqFiNVhcMglBcjVYyKTS0BSLjmzMQWhTlJm/oWzsSFdHoJUHpCpnoxOxe7wKFgorCPOSJISfqtbQHU/KMqKJphURQ8x5DsnToeutea3uOuex0bhiFNdPHOMj5E58csMoHLxdW+dgjWlIFAXqB9E0x0n9tA3NMUlnwjJCeG7G73O0WoUanzxTxq7PmGrXm2K0wkdDgHS4g7gknQ6wOl1Q2g4neOPGQx/iTCZfvOWutgOGLp/2RGTIknFlbdUhXdJvChzxfAWTv7EGZHxK3vGxhRAvUpfGPNBTcp+N567VTR15ChBDc18vesoa643syTe/2bl9ShC5JGa7YoO3GyDL0agr2pHsRc7PXxVe9cKfmPy1z4hKQt1B9rSf84O5QrwioI4larVO3iP8ri9nKWhUMbqWFKK9b/Hb0xADSi5DXrfMVLe+qqz5vtB+QPJBkLrm97wNLY="
  - secure: "QTiGTWgir7e1yjaVb3XO0QZ4ie1RlgEQVa4f1hfhi8T8d+PtDE3WgbT0G2GcJVaY3/fS4rEpXevzHiXgmKmxTNktBhSaHFFAupg5kQ4FNJdTCKpdpq+nyqC/1urxZhwhReSfs/nz0/7Rkf3P0X3e3J4khbkvl7C09MQgJnqfHf+GNPdfzqheQaErk4BFgYAzrXIyrdG1l7B8+Kjqn+P26vFrcq1waq6BVR7aSRtXtafeOgZNGdfkuhQr5unD/j0riFjDLqZ/bk+4isJaj36HKJpA1VTf/89OH2QKKYQrncJYPM0OnPYh8kkOK0/lB9w6BkbaJgV9zEet1va0QIm8Vp6fgfnb9MR6fJcFHX/xWO9bBYb8wuV78fAP01ueM+8D4kL8525voglL7Ke93yPU5jeE014L5W0prboOXnaBkCymDzmhh/t7OkWCcoLHEcVNKQ63w0VNjQRQ+dO3NqwObpPx2cD6hsRAO4XyDAzuXIU9bHAZTPHyfD2cFeMUqn0JNoVmBpl/PIv9BDo3HLqOpwOecta0ze/zVhPa59adMHtZn3ZTT11CfFfIezAr/u3YjpQ8/PqeC2XJYZfaIaKE68EWx9GRG0gPEGCi/8b5BKVMk6+HVd84xwG0sswaAiDxtBN8GhvLGvK8oiPFHgFIE7Xkb3pEUSrfkOf5Z9uKHIE="
  - secure: "PvKOM3AwlqYC+t72tRibct6w9NbA8WamKpfN4pZJAnrE3sQv/Ny/8SSQwOmBC47C+uw7JrMcUz6xDwLfd10bIXbkKKTuDJ+ymc5qmpTv1PtygZlVhioABZiP9kwZDasStOW6R2nRRitZ8e+E+POzmArrE+m3n6R7CJ61mlUPuATXXIiFnNN7uMUvGtEtnzE/LGBzeMCnZ3wR0t4SvWk0NW7Ml5QKbP2cRnIj0vB08TPPTqQVEMLIXxFOOotWWpnU6aACOgNC8ZxKZedB7DgRC8Ty2ifTN/etmTx3AU9eDslxap/SHr3CdwkrR7EwpWGMd67qPbiH23aoqjW6n5Vi9g2zR1qXvwv4gTQgXEcH4JhfSQvb7GQH6t246jYiRcV+0jwPlYXmPiqqKSmRBp/w/MsWuqUWDgDd8sa7Xr2l3zEZBjxWz/riJ+QInbmyEpPaj4yWpir/4GkmjQtaeX97Mrq6dsfyNYQnEqI6qgjBULFRMi3KlRE1dgN//NsRL16YLCmSVc5cOgmwnuhbwcuCkj98+c4Wlm+Z0pHQCt6+I1eMUGgdgB7rl0k9Mny9E0wv1dfJYGLXLbZnXSygPQlBLwE+9k+J+6cdERp4ZRkuaMaRbkiUVGgqgQZURL9qcrchidD/YkbdEaIHAK+onK8BdlqnFJldVBo762npnJD2ZVI="

