sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
    - lcov
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "K2Sj/12yjo9K38nvP7nKz028wqBySE27h+9//XKZxmZY2Ie1lk66V/7weRSc9oXmAQVxo97JxLAXCcTqOR5Mc9nJ8G4RsPoxAwJa7EnLE/5ZLUGZyBOtEX5T+4zYTClvSnNPgcUCqoyrNMEoB0X8w/u7Qim4c4DT3DkrdsaKysI0trlGPOgpnmphUnZ1WRc96s3lF9tI+ORsfsXonP6vbrmuN+dlaRuxr4aUzO4s9J6mvYwbw6rdn4ypFegF721p5TZQUOvz6ZMDUiK0Ea+91DdTUVqWYaHGieQIGh3ewdyvCcCvr5BRLiKRhzoQ0wJW1PkXG81yK0o3cBtW3+J0nSFgqX9r+DdrxQzzXOuz3EF0EBaEF/UIZ+5cAhsNts8B0RVGVU2KIrC5zTnn4m5zN2ulqWVWIrGfmMUG4EIXrAWQuop2CP4JSP9HIj1e9+ngyfaYEakdE2nDWytivr0kYfEOxkX+J1OLlsLsrHkJJrKuaCnID7nDeovHSq5GIIaj6qt2odLmI1g8rkd3/NwxxEEj+YsvFxp7enuDgQVEbcpvPzED7aP5F0mDg6aZAHF6b0kpkxkrFGCJ6J4yP2ybRV9R08gVVyOXnxrEccW7cELXqkF7D3OY4u4hdHk/9Cg41G65tyR+dE97B4RnJuD4r2kZTfA0TVLCXADVkx4YjuM="
  - secure: "nW+s+AL8VNgkXhqHxa64AeOSSZmTBZHBZt3A37UBLEIDmajrev+IM1EBjIGQq22+53AopVLAycESCVUK+83EzYBbs+NVqFvw7IIHnrrPymMxKqXaGit0y7Z/24E3WzgspI9GCnyns0f+GQHM6C3zMMZbgBvBHx17KGpc/QjgmGZ0nKjw0hHfimzFwRc+HUw0vEJnv2Lk8iRIgIdM8pLPFi6IvfNuEzTGOs8HYuMMw/d6el2BKiJNX3IOUbIsHp78xnyGhyTJHQBJbawxGMYD0AhV2GKYIUJg1UOWfaJBDwF1/fWzhhkIjEc93nQhaPKZmFBJNFbL9BMzby4cI/AUMZIqVNDDihCwJTrObCGAPNGplUw6/b0T5A8QWSH8tZXYGGpNc9kRWXKxFAeto1HJutTwIRb9HbT1fv4x0juDAZyNTggAocsBD4KsaxPXmI3uJed/Ms5xQ3rKNDHe6Jx8kSagLpz1v4MEOtdOy8JEDsE9su5bamNhfY3hkdTeVBMY72R4SBzUTDR/LCgPLFdO21Ab2h+P0tUquKKsRfSePSDkE+Ofuy92cK9VPt2oppiJK+HUzPBhiCi1kgjW0Xenxw3qDHzMLQoaMk132yGwyAZmWodNAYtMTpMjAsfKr6O7QDZyB79W5IHyXOVd/5xyEaCxOGu3eUxdh7nhGHueiFg="
  - secure: "WZ/gBviovg3Rm1t590d0BsI8KAQ5XRFUQEkGwVtxOlwqdTEA2R/oKWiwZECpdR7+omsauZY+4rMTSP1nHRFRKeDYrdHfpvodSjPGSPp6mz8PnxEahkn2AKpDDh/r+d69lxSq2vKmrVYN2y6UpW9y41+CMFOpbeEaaUFf+X80CyX2POj5kQAtwo3YFimlKUCRdt1SlPYdFYZaV0WpRL+q0dIdBnSD2UwssLI32qWDq9Y9qbCQ+ftanSKlxmsBGF0jXIdWwl8UXiwDutNawviJMV1+gMnJayn6kZY2RIWv2TiA3lVLe562nGLPNxDcZLyv3iA2AYhVI2AqY5DlXa0mKBKcUsx4yUuKipJ6YIGc1+JlvqnCYq430sruPvepcal+DG4o3UQLA2CQABMPQIWoYiwpEhlRHUhGs1/xwMY3F0TZ/2SfUytM0litGLauLtw9/jCwMu28hlpHmY8W7M/vGMy2IPKXO6+voyGQoKF9Mvm3176MJAVvT7IvqbxId7Gcdwka6PGw3ZRIqXSYiP66gp1xMloRDYx6A0EdInDr1T+VTN4OvXrjN4eptYyDfLh+Jz8QhaFUKQG7ngyjR584JK05Znqhv4xiWl7MsDfqJXXit02sLVZ5nNdtrAVNPL2YRtB5e2f7LEzJ3M5R+hARiZs64ohms2HmCwIyigafCMw="

