sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "gWEBH1dLc02m655aYNn/2ogMiqtwLNQQtKsWaySeeU+Bgi5gzQeC25ZaGesAUqyU94WzsprnFlLayFTSlO790uLIemzhDLWK29UzkKv0uHDq5iRMqATKKfou4sitz1lCSe+pqMKDgRJ92qT1CK1OT26oBeMJBesV1VCsiXdi6BQXd7Izn5iVP3IA3L5TbGCmKp+At4hzD5laUqFuRNzVmGBO9TYW822NNRbV4EA7CL4qILEQb+aLXLZk0DvDDgf/4yv9c7+BOe8K2DMG/QTFh6Li2MJqAnByR05oLxDYjzt+wRpNuHPxitUxw6s6G9gSNo6ALDIVD1vn2qiPkR1oaiW+PzIOeGjDOe4N492IVwGeO+xnGfvwePyWeji7lioPgrHCz3OV6+0SbnUrXSi5dvMzg3gl6XnUza6KHqXPvelXEZcjbkqw8YIhvRQeCoFyKAUruDrkCuxjOqLVUJn55hKKgMb60Fcg55OISvjKiMzGinR31uuRWYoE9lKyDADTjmVb2UXe3Q0qaQh+NpBlBKGqW6+VRoBWsCgSmjwNoWnO766D+Q+hBqXqqCykOacyjI/ddWCaSfgjDoG3U1z3JbRe6AwcNVniYx22VQhgtR/2AyCIZ3bNfBauZw3USEYa/JGJ7u51NHeFVmmqxHOtQc5Uj/CzW8Ukcb6UR5th7jU="
  - secure: "Fp7Lagcide1dG1rgSuhQbH9De0vJ0M2Zlr3XhM1la+H8qibohBa8J/S1w2eczaLx/umWGHXTDdYB+RB3Rro75V/2/QTaw9S1+uJsbMBRxMcRJs0ST6QX7a7NJuY+XkJonMYIw4dg7s+CiIsTk+8/UdGXp4UhU07W/vWeVjU6/6DGp9w4sSfYfQ5cB6VZUTWmJQ7YHPQJdnQFARiwsHq8bmaL46d9Xne1qRJYshqa/r8YbhryH6v+ukJB+kHO9XJmf7gBTiQenaO4dJrtgseby1d2LnrcKJGdU5VBJJ5k4s73Qa/9qsYtF/XZiKVeJH8C9wICJGHF67wq16HAMEf+qA4H+natHWEB+xIzayIma9aiAHKdzXSkIt/nHIuxMu1UI51Srqdu/DNQU49TBh7jm3OuWOhpBrncXqoNA2T6cA4OxS+UgvVLuccYyyfnH3etINyEUR1TKUHnFN5ggeplhf2500h/9j4LXzQ1VWUKr7BCOL6CFOftVZCJ/Ev4iBl15pD+SBQgsmQzqrV+G7r3I6qe9x8aXZRU8qP3/0kW/yMiSGcVK9shl6dNINfMo15VegTVocBun2KKQGHeAW51ZhzZA/rKyzCNdT4RnHoUaQZFH7gMqSru8IMvJt7Lq9Zn/5CBpwap5uq5oomQC0coNCxNO3J9f+oK6o7YqZ4WBJY="
  - secure: "oNSaW6jPJZYL0bfQzUtT4/3WhKRrL8NIVgCv2MbYk0FiKSQ3pNfed939xOVND2ohQZ5CUZo3GJGY/Y8Is+p10WhT3qJ/PfUkWKDA99DI+Hsy7QWU6QiBDblCeeNlaxZ7EKarpjdbdCLyQiyAr1SkU5QXxOnVdEB0xsViohWOA85xz3NbBMvxnoKWqyWQ1rvglwUIC2qaaHismWUzfHWB8h2V4WMuaEY1Me5ACwBUidXaVuT+lLMgEfPZ2hdLngd16+9IG7TcKThmZOlDLpOX3lxWNVFo3+TtM+fOV7FiUDzTDOF0BZQ+KViCM00+CSNu/Z3m/uSBt+9vAiRLjgV/ZvDIqhYXQcd1GRR2Zwl406CY+nUgfNtJIiS354F60d20DdJWVIWxJrL89A2PXhakpZFfiGsQ5e18LQ2BcbV2j/PE1uTZdD+WBrNtJpUpyqzkos88n+crP6iXqE9AsRpxxOM5xI45w4kQlttR3cKO+7SC2rEzvOECopXHDMyHM9qW16QFDVrKNyppbtI2oyX1ZcTecRrD61aL/OFrahTZgmenLqFmw4KJvCu9domDCFrlk4oA4szOSa6LOZy0F6nJLATG1RxDId0eVK3nkVhH4aL8lyHfcHxBFt300TVzDWC4c7dwM7CVsrfvfGCsow9cz0CTqr+5edqnf/A+i3JPlIQ="
  - secure: "MoBhR+7/xS1iR3lNlrgiioj4+PVrjQfbEinyaD71UkNsShm/S1tIaM6XKz4a8bH5qqdD8QTLD9b90VKuPTRuuKoFmkfda82ttKxVGOpAa1ApcO5agwUa2GV83v0H130fMdLaXjxM6aUqLksJxhe6kJNHDmO4hQVuy0zcCCE2LuVGurVuXwiv1P2NRvfs54u6INU58oxkpqQjABtjVZ9yKF6jxyQBMSk1n/Tp4FD7CowfxXESGe7KmrAVpO0x930wm0n1ZktNIvtT3JN29Pp8KfCs5nzANczPuXoVyCSngMCPXfEZFnYBtfuAB2rlIxRa56AhsO0SgrQy/zu7a1MWXytrRVJkpRcVIs/aCQ+6OSHxBtW+U75xIMK0BboYzuZYha3ZLZAXuxHg4M//6RtCFPB/4tKlYEBneQ3Aiq/Nb/mikN50adWvsoRI53u1CpV/Owsyk72Zbo937eKEmEn/jTq24L4AoOPc+A5vtb07xm6lEwfhwO8zFG1PN9X67mgS7m/HEdNk4tPvYharuj7wrzyksecPtwG6OSQ1+sDE7hkN1LCU92GPz6dALbf+zL4E0nsDWzN0dd4iF8P63lOk0plMNsn2h8QT0eheE+rLFMSmFnq11+ZMU2xre/URI026wIA5ZnLNw4z87tCrXjYHwgpw8Ozfz4cTAizPRISk2Xk="

