sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "S7e1LmTQtrNQMdDnzOnq675czad/yk/d2MfaHNugMp39xzNbWe+K1Qgt+1EKwTdrZGc3Uh9U7y2nX/NOYqGyZ3bVBOs+jwS5D0rKfS23Kw7F8ceRDsQH+91d3pTIKXx/itCYgKqYnFWShCbj3emNVRHCALONeajaPl5NvEpdqbl0x7VFCV7iYE7GWlKJ/4Z+F47GMsYDtLsOPuHhPFoB2aBfItCBqBuvIpN6acIev1BOVAKpZEqWvNYwsroU/6EzCZ0CKlH+EurUdU2ki2IhiVpbY41VI3gi8dZWyddiwJsPygfxnZ/8RVWxwA7Ln0Cm4oJppsFsebZPtHHNWhkrkhSk51JF7nO/RT7hH60slNcWQ/J3y8JdCN4AQiwfViaDPNIMx6ubB7IkXmMfvwP0/+uW/j6bFpQ9NY9Xl1pj7eUnccINdsNm0WXLrFsQ2Grf7bYoicr5wXMHVRGUdv6/zykLEvImTwtnnHIwO2bE20ToVaaauXggjsSfTI0d6+DD0Vcj9spL0Pps9aaHhzc+c4Ng4HjMsN6930q9LhIApZIYhobOKktiIXnhDPNImyjEBtVuL47UPXHiVtQ4YHuwbCcEDeO0w7BC76QlCkevGOR6bTJBZrpC57sw7IEaP1s1lXwCE9mggKjHZ4Gb6MBb/PDP43n2YRX5qE7mwrLpcSs="



