sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "U5xMz+/UMIlzDv9uwfzLo9aTaq4K3aUcVgv9+a3zTynSctZZXKXNQ+U+HHK4vVdqxpo/oSA3Y+6B6Zvj+vj/trX6HibAWWtPyAYWZ5iyKUdPjnMlKHR9fAeqpf7XTzkxqBFt10E7OnZpyUN/v8S/H7L/e7V8OI5GOlD2BJFWGDjdT66wA3d8xAblAL8h1OGaLIWAdwxBEnH+rA+j1ERcVQ2gG6nVJcFqrAwJnzYPsDLafkifyJkHoyOKQaHd/ApBMTARcxDFirV30mk1yRdQzcqUyXPHkZSbVKGu42aTOSIpRhkdXiiN+fqr1xLJ4O6bIWKb9JgH+z090Oz885vJVDuLWqqym6IosijT7V2VHz41TqdVhi2e/HpaQVWZi4QUjI5Oj9SbbtZnDMUa7URjXrN/zZzc9VJY66bmdqjeA7of1oXebLCQAHRY4SMbBRqroNgWsqfkA5cjxv3+k5qaR+fwrsy/zj1HMcqDfnF/fdw7BO0M4xbn5xhWOnFnx71yDaPGM4aBMACxS5Zn986CNVbSu+3FAyeB3uS+n2ZLAsMvxF7+q7N8I9TRtmziO0fyPzASTnxhQMTA5KIZTa1oGMO5e9fA1Z1UQ/Tp2XPlHCAPvWmUnyf2p8QRngvStM/ty5uFTi9kVflKu33F6Q/5tPJ8wLvYYVTs8t/geFb8mmA="


