sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "OrVuskyzKoPrQtzUkh+YD7fxv5Ai+GZwwx+X6YoaAiIYXszvtedTor3BcWDYeqf0EGLR/7Hwbv7EYcevUdA3/KXCSBXFQZbZWIwl2cAbhvQ5sK1Ry2jh7b3dYExY79SascH5DEZ6Ms9wqF8onFe8Kj4/U1av1me7ZkMmmQXAn7f6MVn4GVKRDJkV8MSUNWaA7EkxfEq6N6R6dava9pEj5IK1ikzv6aSGpFLkw5YGaUwAN8MxOrvg8OaO0n/H3k+aMI252UjFa0gtayjCzGM7BuoKrQjj642YZlRioSLt46mxJ5bMDH1OaoXrlBAa5KmB5BUUYVHtweK4S+OBoejcRypWyx+yHLJSo8EUFr3k1bO/zJW9Iq+hrq8QRu5/SYrD+MLLPvekDpz4iLHPGRABPFJEPnTduAMryljupwgDevuiNIQ8rqvIfSCQ5J23FtruLOLvqsv1i5PEc14uS8Xewlvm8J8tJU9CiB2OdqEIN3SMhGawyg7E2IOBHVPc0xFWUbETmh4poEMJJkdIrq8q2z9OUFckg+5qcj+2/cBHB4BVgyNR2LrxocgKN876rnP3QhH2lgLsH7W9KszDk+dnCl0ijYUXZsjnUAl0xPSahdU6okXBZFk4K1EJpJJks7rVjAc53DFbzfSBjv759T5WgBTqd3dEg7XpLItQz9fcQk0="

