sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "Ef8lxBAHKUZm2v7etIRCkf6FDGcdFu7OQYWac8acA6Uv+vtf2b7vQtyA9an6LpFUm2ulqxaLwnqoicJihvtWKiChQnyoHsDDFy9ZlkxJ7kl+2pyiW4IbI3MlwNnrxOgtb1tzqAbexigh9SEF28aidEgQngq2jA43wDIGLEMIO9NVj1aPglgUgaVU+e7yscvFpY5pusIZWi76GQG8GT80y7/Rk2LlA9e/mAkiaM0sntQGyWgnph79+dx8xtf9z3nhP8OsQ+xZx881rI6qhJNrpD+ogj6EwAPI8pFWWwUHXAYWtxH4wVvoZAjBcmZXZAObmIZJvHUmtUWVBboUhPt3tS3tlU2Vr8QzyBbVN07T4cZ5T8ePBLLYSfpSWekZLgiFanU+dDWEOlAAs+F5IoQe91lrj+FwH1V0TDtv39eHwth0XG6nKNC9GD04tC01WD0F/95E/kRtxxJAH4sE340LoV+brlVxNRXWQqyo5yiRWd7jaHII7A1W0om9fhVevUYZemZCSkz0eMUvMY7JA4u49rvkjXghYiTLUt/Xfiz0A6xC2KNsrFgd2OcMluC5PaU5VWHZ80M7hwPnPasiVn1keTlqaD2zSgQXgnJ76kC1lpSPzw7XBIp6XEFJVixhbhsvuPWwYinsWlNaG5plR52oY/6cL9J6seMJvIw5d2p+ibI="
  - secure: "SrqgYAYeeSx/WY0Uhyx/HFdBqYXj6m7BanupZyyQvXjXBNmaxrNTfdXpNrdpa+zXKfSVSSxTH3gabrCIc4lFZ+56SplrQl+/DodoDYm5AEfOcG/4sBPg+Y1tt27jIptSqBvAbYv8zNwxDfCnD+lse9QWguXDurl7mPuejIxtJNt+HL23Isq/WV8MJX19W2g04/A1I5WwTghfDC/gBWryR5TqaHyPfbFAdydk4wqnnMaLVu1f8vPE2w2VqRAUAHrrGdlT9Qjqe7It0Aj0G614B33iJ/tx69iItpIXeFrFYbGN8Hz4gC8t8dHJEA/L4J+wiM/QCD+O+p4RW+rzB8PwIE+fstBFyGerP5zBD7Fm5wqekPXc8hrVSbjdyAsGKDrNxWYatkTEF6+G4xs5kEoh4cEzOWonA9tuCaotMD6dnWULaOOWGpEzwQTyX7KLjEyM3hZVAU0S3ABXJDYvJmClU7CwJcF65qTsya1r+j2t3PyRkuBLijTuFIGzvrEiw1A5+BLEcNkc4ciPkGfjn7HBFyI+Xy5ODUpJkBX/AAhCPFCMHfwSoia7UlXuCkqj0CLkdmhRI1IkaUZjezwtlt9MdAIMU2FLtVEdEoxp+RkNsmMWqWVTLQ7C7TOfMLcTyFEXIRM3Y5RklU2DGsc+/TYYx95eTqN7mJZg8Vi1JjiRrow="
  - secure: "CT91ldLFzV2TJD29pjm9aXDDl65JCgVPf44fNZTouk4EmzDNmpDj8PA9yjK3iSYT3/bFX/86qzEC8jKBzpcIznk5bZn03hJN/25saQA43Lcc5vG4IpW3ihTB8pjr3Ytki45VvdkgcqbsrkE94UHeWPWfUv7yDfv1aZNRH5qQ7rDE3mXh7IFR1o3nbyEqRZ8TTRY7BlDzR3QAHNFeLqB+cbkr5+b+xMzmEryJfOL0ek6hYhPpo5+u69BeNUYV6PHgo5TmAZkNrjo0ern9T7yjhk1LXwuIOEI59jrTnDh/3KC38RqL80qRQxC38uS++D+ysL+BruD3+tnaTCV4Z06OPyQHYMfHd8lJq//59jWRdMjyRCLXBR8je0X5B5LpSLADqzHFOkZ8SU0U7SxCn36tRRAsyby6Nhawuj7DdPT9vN2Gamm5yJyDpGCROHybZ+bgThJ7RzoDsBz1yLwopxZsaIkYwibmO+7FjymXaFoL8Flw/hUcKlcg6hR4BDbengL3wozZg4R09j/YU3DTD5I5+3sSSAzTapjJK2VUobGh1OMwNzVKVlkhcEtrgNvxDnsfGlJMgYFtG7wkCUorJzUJ+iekbID9IeXTrG6rVeQ6wYjGnekoO+b3StzT0JG5m5SM0TlWvu07NmmjSYY0JHod8kYNtU8gnhyFUW+9UOfozF0="
  - secure: "D2dZ0PO5vJTQrfwup8P/sLZOqeh8qbFrBvlUe/0M81CId6TzW9G2c0mVavETPJgrVlbUMdzaquvB7vt/eXu7skT7gImjBnH5n9tV0iz0G5kp5WixUFCba8VQzXbrX1FPqEstR+SYnlEtPeyZWwHly6DB/JGMrTnsyffjhAhMEZbQFtM9/QnOEup7UXKpPVSQ9H2coJ1lb/qNnvWv8FoRgRQl2TOvqcBedzZBzbCf+VPFcpZ5AqAMAQUAy4AvX2TABNOJAwJhU4rB4vnrQ5olTtIgSNVsSGBGt1i8y9ffQyPig5WqYJuObhJjYQxLLVeMkwNS+OSE8uzEI6iI/40juVNd1cQU6hOOePPmtW+r66fuzNaXhG6Knhm0hJQtbuiIOeDnw3ZbQxW9riMfKMELlB34gkFwfJ9Iuu3wbGjoWb3E2HUUoYygqKFc8+lGy5c4EGWXal6pglGAEy5jCfXpHV3Ge8wCwuHoI0bRPcUO/s2fN4MwwGpNEsEuITebPUmjaJQtELCjt3pHZ37EPw6M/i4upYLN9h+62XxX9H6eWGlfDxi2tHhhTYRrfgYHwoN5Jzh/FWi8uyLEQNkoooAZILLBZufG3b5+rbUz/K/XVHXGDMHIB7xmTT4rZpp4+Iwy4/cKralRs0WvOJWWV+VTejk7YSMp22flOUoWwCNwFao="

