sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "TdIsj5HwIMMTGhbjYonP6c/q+ljHNdytlYLh1KUR/TpWJ4jfoElwhhX0k8kGI9O91WI9jVEgUQ359CB7EG/GISqXc9NoVVczA8cmHeNi2w76Joie0VHp67IlM4wmBG5r0OkM1GngdtG95kgSpKKERs78fDE7CPbdS/C/HoWVkkXID4AG100xhoBzMasH+3WYUz9MBGzydpWpSnBOpFLlbQZGyv7pmqkQXZKz3JpmbXmq5pkIPBKAaufxmkYVBDo/iktT62KL941BOU5/rAVXpKEgGRvWYn4WX4j9ilMx5rnvPQbuIibKzK+87ZKHhqkM62JVR5z2Dtuceh/JjvQyuQX/5S72luMCW7K2Mq8FVu4gPEIuX6fhWylTr3dJGbo+1tbLFWTevmyXGN0jhgeG1yrbb0vsNWN0/97etQC1MGvZHj/gQiDwMowe1PRU8A03Wum83R3cUOk5qjqLdx57hgcMw7WS2ABsrpHZwear+pE5sz0K/T2fcsgUhG9Q6FKwMGuc3weIXji8hqWt47HQEG5qGR1gRi3ypEJ7Im06pidq18sDivJZF6IOLibWeqj3Ose5A6wgupuEHX7v6tC8CxVavgPDk8/XL4tvgIV8eIOp+ATBDSVPWZjfFteo3MmBIT0tZN/ih6jbbbnkIHL1mUafUkpgx/pLFfbTiBH25WU="

