sudo: required

language: c

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - compiler: gcc
    os: osx
  - compiler: clang
    os: linux

before_install:
- chmod +x *.sh
- "./travis-install.sh"

script:
- "./travis-build.sh"

after_success:
- "./travis-run-test.sh"

addons:
  apt:
    packages:
    - doxygen
  homebrew:
    packages:
    - doxygen
    update: true

env:
  global:
  - secure: "AkUA2E5WVSF4yRDR2b357X0wOsoIAnkYHItIfGBG1wf7w9lEaNZhSVtkyabvfdMBfh/Ij6SPhjPS1GcZZrvpAT4z26cUiVz82C9KlDrmj+qpeAXeBqF4Z9SnM4jtICMJL7bwFFPbZeSKty8lVQINXeiJkcmvlGxAqgy7E7lDHPM028DLaFPzYBwyYN4+Dw37y3CN4l46BVoyXZ1fxvB0Qy3kTGnNudWAQO5gL7QuQuafuyDow5P6+5VUapn57ygSg6OFt9axt2StJ6ELC3VSJoPslvTi1lAu1kltZhDcGJzvrvnLJqug80/WDmJVChZakmePVxy2zTbVPNJOS9wiw/j9AOvZGoQEUL5UNZGfHJY8qmQJwU/u0/lMSozMTDzaAketGLoODXzIHhqgEDubAwd6eQ0D692xrMnto27GR1Txba3EsLf3YHyg/VB3AuvS6lqvB/DkXeAVR8Nu/ah0INv5cvimmwXPrmcM9waBMQimFMluTqAYKauHKO6HOMSD2Nv3uu2jePGGy2NHcrTFVzdal+kb5xhg80Fhp1wwuDeR4U3ia4eYZsRVNB6nKyguw9+emO72fBTz8oHlFjjMlTiTCI4xVLU13FLGkw05tnQoUinKWqh9F7Ww1MMQgwhqn1UuHZ7svpZEm5jg/Y1r5ad2ww0Em1Mgu0aKkYamZ5A="

